{% set name = "logzero" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1435284574e409b8ec8b680f276bca04cab41f93d6eff4dc8348b7630cddf560

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - colorama  # [win]

test:
  imports:
    - logzero

about:
  home: https://github.com/metachris/logzero
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python logging made easy
  description: |
    Robust and effective logging for Python 2 and 3.
  doc_url: https://logzero.readthedocs.io/
  dev_url: https://github.com/metachris/logzero

extra:
  recipe-maintainers:
    - carlodri
    - metachris
