{% set name = "logzero" %}
{% set version = "1.6.2" %}
{% set sha256 = "7d1234dbdef8126b6ace4d15cf8a60418506355b2ad967e117d907026cf4f2b5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - colorama  # [win]

test:
  imports:
    - logzero

about:
  home: https://github.com/metachris/logzero
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python logging made easy
  description: |
    Robust and effective logging for Python 2 and 3.
  doc_url: https://logzero.readthedocs.io/
  dev_url: https://github.com/metachris/logzero

extra:
  recipe-maintainers:
    - carlodri
    - metachris
