travis:
  secure:
    BINSTAR_TOKEN: ZUouz81AVmQmz4uoYoWyJV0GNI3onVnnLsfrfgJnhjVoQJrgwNEe89E/BcbzZQmzvZUz5QJq1KzXVUvYsFR7lbh355erCryUSODEdiFFIijs7l7GwsmhoowR7rJ8m4QVdN7qNc01fyzDXaKOWYzyQg/1R7GheM7VJdN2SCBeAzHx1N19WmvSIl3HSijt6iiHoWGSUYFPLWysaUHMOzsgwu2BpwzYjLH/E1PcC3GsJi1i/eNsgNcenA4Big/c6Zheg8FEllvr0y/8MefjAAUeoZqU/kVx2COBLenLuxywG0Vo6fCRwl/QX90pkz2KVlDYcNtHwuY3snNoJJv+8GzqpWL0xOkuqCnoVlBqNDXV0CHJA9sYw0wR4mPxp9hr9kN891bd5qesTdlBGNej2LWcSjgniglUnQZgXdANS7Xn4gxHXcJe+T/S3Zk8yqesn2D2TS4joSAZnGLo4UVxML4QBLIGfTKrAe8P+fwIo5fFslNN/tm/4GAz4Io3GPyPmG35NIslpsEWic/rgwnr/GssiBy/LqUsh3Ww3EPg93yx/ZtjiluSLGSXbHcOiIklVpaPQUZc3U+EPqXNpZCH+NT8+/wd+ywlrjjh7EF4d9BEy1X/wpLAubsozsjtGd6hTEI7QgcGLfVVpUOJI2my6+mfYLXjkYhY6T8BhiWDkGnG4Rk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
