travis:
  secure:
    BINSTAR_TOKEN: ObNOweH9nGy8qEUtRuQaySkbyaQ3pm17jlR1Z+4K98O5EFZXpm568mGFQ31cAOPcEz4FH+YUPPn/FZC4XFAYFA2Znw85Ku5+W6nyGnRUmQJdLw5SR/Jy32ItdobMkAaS/E6MYGZosjYX3PID1bWpxBlN7zWlQ+hMEUz3fIi8VaBNhyLMrhQ6wNi8MqSPuuGKsAnDP/woXE2edbWnEYvm4q94oIrdAMOAbGNJpS22w0DLFg30bWsvTetcyxW3V24pURYuFtE0tJrHzd+SaMEwXEgdXHR+6BeYFnt8fYUnoCA0zoTp01GwWTwt5sGoDSu6QeiTbl6uYNWKWBS1V2k8q8YCMgORXeWVq+iIeX21RTrYMW8C/Va0jSLwjk8W00ZqLHdBu0BxkgO8fmDA2m4fSJzwwXsa5sNWZokg/GAl1fkaY78sFZBHY4tcUNxRHy/SXsJAkDruKbNtXKoKFTYu9Fau+IU1MltTVsNTs6LPtvq1bouJqPJU5SHewonl78YH6X9D6KT8GCNYx/feRH3SxelTYZu2zBNQOKNcUgEHfhDSPR2pJOXAkRc2rgIhociAhhVh1FvvOf58zM4uBZL6EBqYd6CojZlUcSjta6wHK73q5gRy+Cn4/eRB6lN5iugqhN7pLByIJgsWXDU7DCjmjIPmEZzKSey3eZPe6gmsnqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
