appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Fx/nvgrFEFzu2CvxWCdGbQEgxAgJVg739Ul7ssboYtXFbUdwxnZ5ng61u8dQtVIuD3YcCkvpgWtGT+FYB874IRs1T0MJTAkw+F27v8W/gBP1rnYr1F3OCt7ZLfD8s/df+AXVmx00xj+9osn8UDDca5sYLVL25uaEUwHWJgQp8qnXdhqiirK97M8LxdSqAdG7h9y31oDzSPPwoKteZRJsuKGM87dJOPhHdo193TALffrxGebjny4HLLRXMg434niMofW/Gh+m1C+yBumfFSsNWpo+8juTyzte/hI0pdCxV5m7yam0CCI5Pa3FMHgEVRMMxQtKZg1Kx6VNdLr7EMby9ZFZANrR5JnTNlbfamcYPNKYXYbTIa+OT8tGL1R0yvYMZkWukeB1VqCydDORlQnM5MmVtp/ejdFbZgBnTMHjyhlE3MLjqvDrrr4vHY/ELYZngIj3vGzn2N21Hvi5zkwYxZJzhdrpZ9b6YOjVsLRwDcowOZZ/L6LPU7d/sFinsargm66JVFG3hDOl+wSQdzwqWZ+TJECqq9FErq+pRxtoh1fkOKDiw4radbvk9wEQtCvUm3z7IMG28UXYcX1aFBrbB5Qy+2rj0s+yT7Gu0ORtl0TVoI25oMj7v48BN1ZqmzJgXd38DpJWbbVJxAHnJfmrZOVx13XkNKdkFSTjJMkwUMc=}
